### ISSUE TITLE
Feature Request: Support eslint-plugin-import config

### ISSUE THREAD

**Issue by dgcoffman** [bfncs/codemod-imports-sort#1]
Would be amazing if this codemod could format code so it passes eslint's import order rule.

https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md

```
"import/order": [
      "error",
      {
        "newlines-between": "always",
        "groups": [
          "index",
          "sibling",
          "parent",
          "internal",
          "external",
          "builtin"
        ]
      }
    ]
```

**Comment by bfncs** [comment]
Great idea, I'll look into supporting the same configuration options as the import/order rule.

**Comment by bfncs** [comment]
I just release v0.4.0 that adds the ability to pass a JSON file that defines a custom sorting order with the [`sortConfig` flag](https://github.com/bfncs/codemod-imports-sort/tree/v0.4.0#--sortconfig-filejson).

For your example create a file with the following content somewhere and pass it to the codemod using the `sortConfig` flag, e.g. `codemod-sort-imports --sortConfig config.json path/to/file-to-be-sorted.js`:

```json
{
	"groups": [
		"index",
		"sibling",
		"parent",
		"internal",
		"external",
		"builtin"
	]
}
```

I don't currently see discovery of your current eslint config in the scope of this project. I'm going to look how to get this better integrated with eslint (e.g. by using the functionality as `--fix` feature directly) in the future.
