### ISSUE TITLE
Errors on running

### ISSUE THREAD

**Issue by julienfroidefond** [bfncs/codemod-imports-sort#9]
Hi,
First, when I installed it I had this error on running 

`ERROR Transform file /home/julien/Sites/theRepo/dist/index.js does not exist `

I created the missing file, and when rerun ; 

```
ERR app/components/Nav/components/LeftMenuList/LeftMenuList.js Transformation error
TypeError: transform is not a function
All done. 
Results: 
1 errors
0 unmodified
0 skipped
0 ok
```
Could you help me please on this issue ?

Thank you !

**Comment by bfncs** [comment]
I would say you didn't install this tool and `jscodeshift` correctly. What exactly did you try?

Try adding it to your project with `yarn add codemod-imports-sort` or `npm install codemod-imports-sort` and call it with `yarn codemod-imports-sort` or `npm codemod-imports-sort`.

**Comment by stevus** [comment]
I have the same issue - tried to use via npx as well as @bfncs suggestion but same result.
